name: "Linting and testing workflow"

on: push # Run the workflow on push events - dokumenter i readme
jobs: # Define a job that runs on Ubuntu
    linting: # Name the job "linting"
        runs-on: ubuntu-latest # Use the latest version of Ubuntu
        steps: # Define the steps that make up the job
            - uses: actions/checkout@v4 # uses the step "Checkout"
            - name: install packages # Name the step "install packages"
              run: npm install # Run the command "npm install"
            - name: lint # Name the step "lint"
              run: npm run lint # Run the command "npm run lint"
              

            
